from pathlib import Path

DATA_ROOT = Path("/home/jupyter/project/data")
PREPARED_ROOT = DATA_ROOT / "prepared_10m"

FULL_MASK_PATH = DATA_ROOT / "mask_aligned_to_image.tif"
MASK_FINAL_PATH = PREPARED_ROOT / "_shared" / "mask_final_clip.tif"
BUILD_MASK_FROM_FULL = False

EXPERIMENT_NAME = "good_dates_stratified_large_focus_tversky"
RUN_ONLY_DATES = ["0512", "0718", "0904", "0907", "0909", "0120", "0402"]
DATE_WEIGHTS = {d: 1.0 for d in RUN_ONLY_DATES}
RUN_NAME = "exp_good_dates_unetpp_stratified_large_focus_tversky_v1"

SEED = 42
DEVICE = "cuda"

CHANNEL_NAMES_CURRENT_STACK = ["B1", "B2", "B3", "B4", "B5", "B6", "B7", "B8", "B8A", "B9", "B11", "B12"]
DROP_CHANNEL_IDXS_1BASED = [1, 12]
KEEP_CHANNEL_IDXS_1BASED = [
    i for i in range(1, len(CHANNEL_NAMES_CURRENT_STACK) + 1)
    if i not in DROP_CHANNEL_IDXS_1BASED
]
KEEP_CHANNEL_NAMES = [CHANNEL_NAMES_CURRENT_STACK[i - 1] for i in KEEP_CHANNEL_IDXS_1BASED]
IN_CHANNELS = len(KEEP_CHANNEL_IDXS_1BASED)

NUM_CLASSES = 1
ENCODER_NAME = "resnet34"
ENCODER_WEIGHTS = None

TILE_SIZE = 256
TRAIN_STRIDE = 128
EVAL_STRIDE = 256

MIN_VALID_FRACTION_TRAIN = 0.30
MIN_VALID_FRACTION_EVAL = 0.20
KEEP_EMPTY_TRAIN_FRACTION = 0.02

MIN_POS_PIXELS_EVAL = 200
TINY_POS_CANDIDATES_TO_COMPARE = [100, 200, 400, 800]

DENSITY_BINS = [0, 25, 100, 200, 500, 2000, 10**12]
DENSITY_BIN_NAMES = ["empty", "tiny", "weak", "medium", "large", "very_large"]

SPLIT_MODE = "stratified_density_bands"
N_SPATIAL_BANDS = 7
BUFFER_BANDS = 1
MIN_MEDIUM_WINDOWS_PER_SPLIT = 2
MIN_LARGE_WINDOWS_PER_SPLIT = 2

CLIP_MIN = 0.0
CLIP_MAX = 20000.0
SCALE_DIV = 10000.0
NODATA_VALUE = 65535

POS_WEIGHT = 4.0
BATCH_SIZE = 8
NUM_WORKERS = 2
PIN_MEMORY = True

LR = 1e-3
WEIGHT_DECAY = 1e-4
NUM_EPOCHS = 20
EARLY_STOPPING_PATIENCE = 6

TVERSKY_ALPHA = 0.30
TVERSKY_BETA = 0.70
BCE_LOSS_WEIGHT = 0.40
TVERSKY_LOSS_WEIGHT = 0.60

BEST_MODEL_DIR = PREPARED_ROOT / "_training_runs"
BEST_MODEL_PATH = BEST_MODEL_DIR / f"{RUN_NAME}_best_by_val_tversky_pos.pt"

N_VIS_EXAMPLES_PER_DATE = 3

FULL_RASTER_DATE = "0904"
FULL_RASTER_STRIDE = 128
FULL_RASTER_BATCH_SIZE = 8

FULL_SWEEP_THRESHOLDS = [0.30, 0.35, 0.40, 0.45, 0.50, 0.55, 0.60, 0.65, 0.70, 0.75]
FULL_SWEEP_MIN_COMPONENT_AREAS = [0, 100, 300, 500, 800, 1000]

FINAL_FULL_RASTER_THRESHOLD = 0.75
FINAL_FULL_RASTER_MIN_COMPONENT_AREA = 0

OUTPUT_ROOT = Path("outputs")
FIGURE_DIR = OUTPUT_ROOT / "figures"
TABLE_DIR = OUTPUT_ROOT / "tables"
CHECKPOINT_DIR = OUTPUT_ROOT / "checkpoints"
